### PR TITLE
Feature/fix pages

### PR DESCRIPTION
**Pull request by Vineethaveerapu**
added main content in about page and fixed media query for that page

### CODE REVIEW

**Review by Svpriyaa2808 — APPROVED** [review]
looks good

**Review by Kavitha0691 — COMMENTED** [review]
about page i couldnt scroll down, need to fix that

**Comment by Vineethaveerapu** [comment]
i fixed the issue

**Comment by Svpriyaa2808** [comment]
sidebar want to fix

**Pull request merged**
